apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- istio-noauth.yaml
namespace: kubeflow
images:
- name: docker.io/istio/proxy_init
  newName: 10.86.27.21:30001/kubeflow/istio/proxy_init
  newTag: 1.4.6
- name: docker.io/istio/kubectl
  newName: 10.86.27.21:30001/kubeflow/istio/kubectl
  newTag: 1.4.6
- name: docker.io/istio/galley
  newName: 10.86.27.21:30001/kubeflow/istio/galley
  newTag: 1.4.6
- name: docker.io/istio/proxyv2
  newName: 10.86.27.21:30001/kubeflow/istio/proxyv2
  newTag: 1.4.6
- name: grafana/grafana
  newName: 10.86.27.21:30001/kubeflow/grafana/grafana
  newTag: 6.3.6
- name: docker.io/kiali/kiali
  newName: 10.86.27.21:30001/kubeflow/kiali/kiali
  newTag: v1.9
- name: docker.io/istio/mixer
  newName: 10.86.27.21:30001/kubeflow/istio/mixer
  newTag: 1.4.6
- name: docker.io/istio/pilot
  newName: 10.86.27.21:30001/kubeflow/istio/pilot
  newTag: 1.4.6
- name: docker.io/prom/prometheus
  newName: 10.86.27.21:30001/kubeflow//prom/prometheus
  newTag: v2.11.1
- name: docker.io/istio/citadel
  newName: 10.86.27.21:30001/kubeflow/istio/citadel
  newTag: 1.4.6
- name: docker.io/istio/sidecar_injector
  newName: 10.86.27.21:30001/kubeflow/istio/sidecar_injector
  newTag: 1.4.6
- name: docker.io/jaegertracing/all-in-one
  newName: 10.86.27.21:30001/kubeflow/jaegertracing/all-in-one
  newTag: '1.14'
